# Generated by Django 4.1.7 on 2023-02-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_account', models.CharField(max_length=200, unique=True, verbose_name='telegram account for communication')),
                ('subscription_start_date', models.DateField(verbose_name='date of starting subscription')),
                ('subscription_end_date', models.DateField(verbose_name='date of ending subscription (inclusive)')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_account', models.CharField(max_length=200, unique=True, verbose_name='telegram account for communication')),
                ('is_verified', models.BooleanField(default=False, verbose_name="is order finished from client's point of view")),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question about the task from contractor')),
                ('answer', models.TextField(blank=True, verbose_name='answer about the task from client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(verbose_name='description of the request from client')),
                ('access_info', models.CharField(max_length=400, verbose_name='web site access information')),
                ('date_estimation', models.DateField(verbose_name='estimation date of completing job from contractor')),
                ('is_finished_by_contractor', models.BooleanField(default=False, verbose_name="is order finished from contractor's point of view")),
                ('is_finished_by_client', models.BooleanField(default=False, verbose_name="is order finished from client's point of view")),
                ('date_closed', models.DateField(verbose_name='date of closing the order by client')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.client', verbose_name='client')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.contractor', verbose_name='contractor')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.question', verbose_name='question')),
            ],
        ),
    ]
