# Generated by Django 4.1.7 on 2023-02-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of ending subscription (inclusive)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of starting subscription'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.contractor', verbose_name='contractor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_closed',
            field=models.DateField(blank=True, null=True, verbose_name='date of closing the order by client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_estimation',
            field=models.DateField(blank=True, null=True, verbose_name='estimation date of completing job from contractor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.question', verbose_name='question'),
        ),
    ]
