# Generated by Django 4.1.7 on 2023-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0002_alter_client_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='permission to get orders is granted?'),
        ),
    ]
