# Generated by Django 4.1.7 on 2023-02-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0003_alter_contractor_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.contractor', verbose_name='contractor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='PHP_support_admin.question', verbose_name='question'),
        ),
    ]
