# Generated by Django 4.1.7 on 2023-02-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0004_alter_order_contractor_alter_order_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='PHP_support_admin.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='PHP_support_admin.contractor', verbose_name='contractor'),
        ),
    ]
