# Generated by Django 4.1.7 on 2023-02-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0006_remove_order_question_order_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='chat id to send messages to client'),
        ),
        migrations.AddField(
            model_name='order',
            name='contractor_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='chat id to send messages to contractor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='order', to='PHP_support_admin.question', verbose_name='question'),
        ),
    ]
