# Generated by Django 4.1.7 on 2023-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0007_order_client_chat_id_order_contractor_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_rate', models.PositiveIntegerField(verbose_name='salary (rub) to contractor for 1 order')),
            ],
        ),
    ]
