# Generated by Django 4.1.7 on 2023-02-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0008_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_estimation',
        ),
        migrations.AddField(
            model_name='order',
            name='estimation',
            field=models.CharField(blank=True, max_length=200, verbose_name='estimation date of completing job from contractor'),
        ),
    ]
