# Generated by Django 4.1.7 on 2023-02-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0009_remove_order_date_estimation_order_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='PHP_support_admin.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='PHP_support_admin.contractor', verbose_name='contractor'),
        ),
    ]
