# Generated by Django 4.1.7 on 2023-02-19 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0010_alter_order_client_alter_order_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='PHP_support_admin.order', verbose_name='question about the order'),
        ),
    ]
