# Generated by Django 4.1.7 on 2023-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHP_support_admin', '0012_order_date_opened_alter_contractor_tg_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_order_quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
